# app/schemas/persona.py
from pydantic import BaseModel, Field
from typing import Optional, List
import uuid
# from datetime import datetime # Uncomment if you want to add timestamps

class PersonaBase(BaseModel):
    """Base schema for a Persona, used for creation and common attributes."""
    name: str = Field(..., min_length=1, max_length=100, description="Name of the persona")
    description: Optional[str] = Field(None, max_length=500, description="Brief description of the persona")
    traits: List[str] = Field(default_factory=list, description="List of traits describing the persona")
    goals: List[str] = Field(default_factory=list, description="List of goals for the persona")

class PersonaCreate(PersonaBase):
    """Schema for creating a new Persona (input model for POST requests)."""
    # No additional fields needed for creation beyond PersonaBase,
    # as the ID will be generated by the backend.
    pass

class PersonaUpdate(BaseModel):
    """Schema for updating an existing Persona — all fields optional for partial updates."""
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=500)
    traits: Optional[List[str]] = None
    goals: Optional[List[str]] = None

class DerivedPersonaSuggestion(BaseModel):
    """Schema for a persona automatically derived from chat history analysis."""
    name: str = Field(..., description="Suggested persona name")
    description: str = Field(..., description="Why this persona emerged and what it represents")
    traits: List[str] = Field(..., description="Identified traits/characteristics")
    goals: List[str] = Field(..., description="Goals this persona pursues")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score 0-1")
    sample_messages: List[str] = Field(..., max_length=5, description="Representative messages that define this cluster")
    message_count: int = Field(..., ge=1, description="Number of messages in this cluster")

class PersonaInDB(PersonaBase):
    id: uuid.UUID = Field(..., description="Unique identifier of the persona")
    user_id: str = Field(..., description="Owner of this persona")

    class Config:
        from_attributes = True